final products = [
  {
    'id': '0',
    'title': 'Wild Army T-shirt(Originals)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_1.jpg',
    'company': 'Originals',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': '1',
    'title': 'Wild Army T-shirt(WILD)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_2.jpg',
    'company': 'WILD',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': '2',
    'title': 'Wild Army T-shirt(WILD)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_3.jpg',
    'company': 'WILD',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': '3',
    'title': 'Wild Army T-shirt(Originals)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_4.jpg',
    'company': 'Originals',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': '4',
    'title': 'Wild Army Model(Andre)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_5.jpg',
    'company': 'Models',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': '5',
    'title': 'Wild Army Model(Lolo)',
    'prices': 30,
    'imageUrl': 'assets/images/wild_6.jpg',
    'company': 'Models',
    'sizes': ['S', 'M', 'L', 'XL'],
  },
];
